baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "T.J. Barbour"
theme = "startbootstrap-clean-blog"

[author]
  name = "T.J. Barbour"

[params]
  DateForm = "Mon, Dec 24, 2015"
  Description = "My Personal Website & Blog"
  Author = "T.J. Barbour"
  email = "tjbarbour@gmail.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/tjbarbour"
[[params.social]]
  title = "github"
  url = "https://github.com/tjbarbour"
[[params.social]]
  title = "stackoverflow"
  url = "http://stackoverflow.com/users/37207/tjb"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180